"""empty message

Revision ID: ebf332a17372
Revises: 162b173c91e1
Create Date: 2019-11-15 14:53:10.082912

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebf332a17372'
down_revision = '162b173c91e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('city', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_city'), 'user', ['city'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_city'), table_name='user')
    op.drop_column('user', 'city')
    # ### end Alembic commands ###
